---
language: ruby
cache: bundler
script: xvfb-run make test
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
gemfile:
  - Gemfile
  - gemfiles/rails-4.2.gemfile
  - gemfiles/rails-5.0.gemfile
  - gemfiles/rails-5.1.gemfile
  - gemfiles/rails-5.2.gemfile
  - gemfiles/rails-master.gemfile
matrix:
  allow_failures:
    - gemfile: gemfiles/rails-master.gemfile
